import random

print('Welcome to the game.')
print('The aim is to try and guess the correct integer generated by the program.')

r = random.randrange(1,11) # Random integer generator

guess = input('Please guess an integer from 1 to 10: ') # Ask for a guess
guess = int(guess)

#print(guess == r) #Print True or False

if guess == r: # If statement to have a different answer to the boolean
    print('Well done! You have guessed correctly!')
else:
    print('Bad news, you have guessed incorrectly. The correct answer was ' + str(r) + '.') # Give the correct answer if wrong.